### ISSUE TITLE
more on DSA & ECDSA

### ISSUE THREAD

**Issue by user318** [stribika/stribika.github.io#20]
Here described one more reason not to use DSA & ECSDA:
http://security.stackexchange.com/questions/5096/rsa-vs-dsa-for-ssh-authentication-keys/

> Also, DSA and ECDSA have a nasty property: they require a parameter usually called k to be completely random, secret, and unique. In practice that means that if you connect to your server from a machine with a poor random number generator and e.g. the the same k happens to be used twice, an observer of the traffic can figure out your private key.

I think it would be good to mention this in your awesome article too.

**Comment by stribika** [comment]
I should add the bit about key recovery because I think it's actively used and interesting connections are then MiTM'ed. Client randomness is probably more… random, so this is most dangerous when the client combines password authentication with password reuse.

Bad entropy on either server or client side also completely breaks the key exchange. This makes passive eavesdropping possible which is the most scalable of all, really the only way they can "collect it all".

I will write an a new post focused on entropy and random number generation when I have some time. I'm currently gathering information and experimenting with various options.
